### ISSUE TITLE
Alternative distribution channel via conda

### ISSUE THREAD

**Issue by zzhengnan** [nedbat/aptus#1]
@nedbat Thanks for this inspired tool! Would you be open to the idea of creating a conda package out of it, so that we can have a second channel of distribution besides `pip`? I'm happy to do the work.

**Comment by nedbat** [comment]
I have no idea what's involved in a conda distribution.  I can take a look at pull request if you make one.

**Comment by zzhengnan** [comment]
No code changes are required in this repo. Instead, the pull request will be opened in a centralized repo that governs all conda packages. Here's the PR https://github.com/conda-forge/staged-recipes/pull/15837 that, upon merging, will allow Aptus to be distributed as a conda package for Windows, maxOS and Linux (including the compiled C extension for each platform).

A few questions for you
1. Are you okay with Aptus being distributed as a conda package, in addition to as a PyPI package?
2. If so, what's the licensing requirement? More details here https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually
3. Would you like to be added as a [recipe maintainer](https://github.com/conda-forge/staged-recipes/pull/15837/files#diff-b5086f106ae0b1db5355fb634575a559365b79c04e1ff6210cdc9ddf6f76c906R64-R66) ("recipe" is just conda parlance for "specifications that govern how a package is to be built and distributed")? I'm more than happy to maintain the recipe myself but, seeing you are the package author, want to give you the option of at least being able to modify the recipe if needed

Here's some general information about creating conda packages
- https://conda-forge.org/
- https://conda-forge.org/docs/maintainer/adding_pkgs.html#contributing-packages
